[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci", "composer install --optimize-autoloader --no-dev --no-interaction"]

[phases.build]
cmds = ["npm run build", "php artisan migrate --force", "php artisan config:cache", "php artisan route:cache"]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
